use_frameworks!

target 'DFLogManager_Example' do
  pod 'DFLogManager', :path => '../'

  target 'DFLogManager_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            #config.build_settings['ENABLE_BITCODE'] = 'NO',
            config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        end
    end
end
